apiVersion: v1
kind: Service
metadata:
  name: food-service
  namespace: production
  
spec:
  selector:
    app: food-oredering-app                       # this lable is your deployment metadata label
  ports:
    - protocol: TCP
      port: 80                       # cluster port / host port / service port
      targetPort: 5000  