apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-ordering-deployment
  labels:
    app: food-ordering
spec:
  replicas: 2
  selector:
    matchLabels:
      app: food-ordering
  template:
    metadata:
      labels:
        app: food-ordering
    spec:
      containers:
      - name: food-ordering
        image: devshubh2204/food-oredering:latest
        ports:
        - containerPort: 5000

